services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    environment:
      NODE_ENV: production
      db_host: db
      db_port: 5432
      db_name: finance
      db_pwd: postgres
      db_usr: postgres
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/server
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount an initialization SQL script
  client:
    build:     
      context: ./client
      dockerfile: Dockerfile.client
    ports: 
      - 1234:5173
    volumes:
      - ./client:/app/client




